#ifndef AUTO_FOREX_BOT_ASSET_TYPES_MQH
#define AUTO_FOREX_BOT_ASSET_TYPES_MQH

enum ENUM_AFB_ASSET
{
   AFB_ASSET_AUTO      = 0,
   AFB_ASSET_FOREX     = 1,
   AFB_ASSET_CRYPTO    = 2,
   AFB_ASSET_COMMODITY = 3,
   AFB_ASSET_STOCK     = 4,
   AFB_ASSET_INDEX     = 5
};

#endif // AUTO_FOREX_BOT_ASSET_TYPES_MQH
